_wandb:
    value:
        cli_version: 0.24.0
        e:
            onln5u4zvzttpgky83ix6cqcr1i6ncs1:
                codePath: src/mlops_project/train.py
                codePathLocal: src/mlops_project/train.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1081101176832"
                        used: "28762849280"
                email: s196050@dtu.dk
                executable: /home/mejse/miniconda3/envs/mlops_project/bin/python
                git:
                    commit: ee0353baed449376f3a03ba35c28b5abdde745d0
                    remote: https://github.com/rikkeals/MLOps_Project.git
                host: Teis-Laptop
                memory:
                    total: "7166164992"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/mejse/dtu/MLOps_Project/src/mlops_project/train.py
                python: CPython 3.12.12
                root: /home/mejse/dtu/MLOps_Project
                startedAt: "2026-01-23T15:16:42.496243Z"
                writerId: onln5u4zvzttpgky83ix6cqcr1i6ncs1
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 50
                - 105
            "2":
                - 1
                - 50
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
dataset_id:
    value: 621
device:
    value: cpu
fold:
    value: 0
nnunet_config:
    value: 2d
trainer:
    value: nnUNetTrainer_5epochs
